version: '2'
services:
        web:
                build: .
                restart: always
                command: npm run start
                volumes:
                        - .:/usr/app/
                        - /usr/app/node_modules
                ports:
                        - "3000:80"
                environment:
                        PORT: 80

